### PR TITLE
Conditionalize Navigator access

### PR DESCRIPTION
**Pull request by rillian**
Attempt to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1228721

### CODE REVIEW

**Comment by rillian** [comment]
@RickEyre does this look reasonable to you?

**Comment by rillian** [comment]
New push uses typeof per Jesse Ruderman's suggestion. Matches what we do for other existence checks.

**Comment by rillian** [comment]
r? @kinetiknz

Can you review this for me please?

**Comment by kinetiknz** [comment]
LGTM r+

**Pull request merged**
