### PR TITLE
Default cue.position to "auto"

### PR DESCRIPTION
**Pull request by johnBartos**
Fixes https://github.com/mozilla/vtt.js/issues/354

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
FYI: this PR changed `dist/vtt.js` rather than `lib/vtt.js` ([see diff](https://github.com/mozilla/vtt.js/pull/355/commits/c45552bfb59cc1620f6644cb1f6c9e47b1ca090d)). As such, the changes from this PR will be lost whenever a new distribution is built. You probably want to port these changes to `lib/vtt.js`.

**Comment by johnBartos** [comment]
Oops, thanks @MattiasBuelens! https://github.com/mozilla/vtt.js/pull/357

**Comment by rillian** [comment]
@MattiasBuelens Forgive my ignorance, but why are the `dist` versions in version control at all?

**Comment by gkatsev** [comment]
Bower requires that the dist be checked in or at least available in the tag.
In videojs, we have a custom build that when we want to do a release, it tags the version in a separate branch that doesn't get merged back into master. Don't necessarily recommend this approach, but that's how we solved it.

**Comment by rillian** [comment]
Wierd. Ok, thanks.

**Pull request merged**
