### PR TITLE
package.json prep for v0.13.0

### LINKED ISSUE #356: Build dist & update npm to include latest fixes
There's been 4 PRs merged since the last dist build, including a fix for a breaking change (https://github.com/mozilla/vtt.js/pull/355). The npm package needs to be updated.

@rillian 

If you guys are looking for a maintainer I'd be happy to pitch in. We use vtt.js in jwplayer so I'm pretty familiar with it.

### PR DESCRIPTION
**Pull request by rillian**
This should land after #355 and `grunt build` to fix #356.

### CODE REVIEW

**Comment by johnBartos** [comment]
@rillian Looks good to me

**Comment by benjaoming** [comment]
+1, I've tried building and using #359 with video.js which fixes my Firefox 50 issues. Please include this PR in 0.13.0 :)

**Comment by rillian** [comment]
Ok. I've merged #359. Rebased the version bump. Will merge and publish when tests pass.

**Pull request merged**
