### PR TITLE
Switch the RTL characters array to a ranges array

### PR DESCRIPTION
**Pull request by gkatsev**
Not having the complete array in the source but instead, just the
possible ranges has a size saving of about 15Kb.
In addition, usage was change to a function called 'isStrongRTLChar'
which makes the code clearer and more readable.

### CODE REVIEW

**Comment by RickEyre** [comment]
@gkatsev awesome! Can you squash the two commits? We don't want any broken builds. Looks good after that.

**Comment by gkatsev** [comment]
Sure.

**Comment by gkatsev** [comment]
Squashed.

**Comment by gkatsev** [comment]
@RickEyre hey, any updates on this? Thanks!

**Comment by gkatsev** [comment]
Any updates on this?

**Comment by rillian** [comment]
@RickEyre said it looks good and it passes tests, so merging.

**Comment by gkatsev** [comment]
Sweet!

**Comment by RickEyre** [comment]
Thanks @rillian @gkatsev

**Pull request merged**
