### PR TITLE
= Tailing Commas in JSON IE8 Error Fix

### PR DESCRIPTION
**Pull request by pcting**
- Fix for videojs/video.js#1943

### CODE REVIEW

**Comment by RickEyre** [comment]
Ha, wow. Thank you! Can you remove `dist/*` changes? We run a build step which bumps the version at the same time on releases. I'll generate the build after we merge this.

**Comment by pcting** [comment]
@RickEyre yup, I reworked the commit

**Comment by gkatsev** [comment]
the esnext/node options for jshint seem to make it ignore that. Also, jshint 3.0 will be removing all *styling* options. There's JSCS for stylistic things: http://jscs.info/, it has a `disallowTrailingComma` option.

**Comment by RickEyre** [comment]
@gkatsev ah I see. Thanks!

**Comment by RickEyre** [comment]
I'll publish this as soon as possible.

**Comment by RickEyre** [comment]
Should be published now.

**Comment by pcting** [comment]
@RickEyre thanks!

**Pull request merged**
