### PR TITLE
Default cue.position to auto - in the right file

### PR DESCRIPTION
**Pull request by johnBartos**
PR'd this https://github.com/mozilla/vtt.js/pull/355 against dist by mistake.

### CODE REVIEW

**Comment by rillian** [comment]
@johnBartos lots of `Error: Failed JSON diff` from travis. Looks like the tests need updating for the new default as well?

**Comment by johnBartos** [comment]
@rillian Thanks getting around to it now

**Comment by johnBartos** [comment]
Only issue I'm seeing is that the jshint task is failing : `Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.`

These tests are also failing without my change. I'll look into it but I'm not sure what's wrong

**Comment by rillian** [comment]
I get the `jshint:files` error from `npm test` locally too. I think it's an incompatibility with modern node. The tests pass on travis with node 0.10. Maybe try `nvm install 0.10` like the travis job?

**Comment by johnBartos** [comment]
https://github.com/mozilla/vtt.js/pull/359

**Pull request closed without merging**
